apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadualv6707-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadualv6707-tenant-component
    app.kubernetes.io/part-of: loadualv6707-tenant-app
  name: loadualv6707-tenant-component
  namespace: loadualv6707-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadualv6707-tenant-component
    weight: null
status: {}
